name: marv-chat

services:
  postgres:
    image: postgres
    container_name: marv-chat-postgres
    environment:
      POSTGRES_DB: marv-chat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - marv-chat_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  marv-chat_postgres_data:
